#
server:  
  port: 8090  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8
  context-path: /xlsServer
spring: 
  http.encoding.force: true
  http.encoding.charset: UTF-8
  http.encoding.enabled: true
  jpa:
    hibernate:
      naming:
        # 对象模型显示指定列名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
  datasource: 
    url : jdbc:mysql://localhost:3306/xlsserver
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
    